name: pixart
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^3.1.0
  mobx:
  flutter_mobx:
  get_it:
  
  image: ^2.1.4
  flare_flutter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+4
  keyboard_visibility: ^0.5.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:
  flutter_colorpicker: ^0.2.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/flare/
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/BrandonGrotesque-Black.ttf
          weight: 800
        - asset: assets/fonts/BrandonGrotesque-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/BrandonGrotesque-Bold.ttf
          weight: 700
        - asset: assets/fonts/BrandonGrotesque-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BrandonGrotesque-Medium.ttf
          weight: 500
        - asset: assets/fonts/BrandonGrotesque-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BrandonGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/BrandonGrotesque-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/BrandonGrotesque-Light.ttf
          weight: 300
        - asset: assets/fonts/BrandonGrotesque-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BrandonGrotesque-Thin.ttf
          weight: 100
        - asset: assets/fonts/BrandonGrotesque-ThinItalic.ttf
          weight: 100
          style: italic
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
